### ISSUE TITLE
Un-readable output - commit 020bf1e257

### ISSUE THREAD

**Issue by akonkol** [qistoph/CdpSniffino#1]
I have an arduino Ethernet with poe module, I am using an FTDI friend for serial connectivity.  I just checked out commit 020bf1e257 verified and uploaded to my board.

When connected to a cdp enabled switch and using serial monitor to get cdp results I get gibberish:

"éuuuuuðuuttéuWuttuøttwuuwWttuutuøuuxttéxtttWwuuètwyutWtèuuøutttðwytutuwëuuøøëtwètuYtéwuuuétuttututtttðtYxuUtðttWWtwuððutuWutttwuuuttøutuuuøutxtðttttutUtuuøuutwttWuwttwUuwuèttuððttuutuxtøøuuðuuttxttttwtWututtUttuuuwuuytWuuuttutuutxuuøtwuxUuWøyututtéttuwutuøutuuéuwtøwøutðttwutttywxëtuwtutuwuuututttWuuuytuuuuèuuuxðutWtuètuxøuttttttðuu h)q=S¬lðl9p==0±} 1}"

What could I be doing wrong? should I check out a different commit?

**Comment by qistoph** [comment]
It looks like your serial speeds don't match.
In the code I'm using 115200 bits/second. You'll either have to change the speed in your serial monitor, on your computer, to match this speed, or change it in the Arduino source code to match the speed your computer is using.

If that doesn't resolve the problem, try the new 'NoLcd' branch - ae7ac0af33c5651dc8729f0180a7c53a967daee0. This has a few bug fixes that Arduino didn't warn about.

Please let me know if this resolves your issue.

**Comment by akonkol** [comment]
I should've known better, thanks! I've got it working.
